"""Initial regulatory pipeline tables

Revision ID: 5f4dff226bfa
Revises: 
Create Date: 2026-01-10 22:49:14.547686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f4dff226bfa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('section_301_rates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_301_no_active_overlap'), sqlite_where=sa.text('effective_end IS NULL'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('section_301_rates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_301_no_active_overlap'), ['hts_8digit', 'chapter_99_code'], unique=1, sqlite_where=sa.text('effective_end IS NULL'))

    # ### end Alembic commands ###
